language: scala
scala:
  - "2.12.8"
jvm:
  - openjdk8
install:
  - wget https://archive.apache.org/dist/spark/spark-2.2.3/spark-2.2.3-bin-hadoop2.7.tgz
  -
script:
  - tar xzf spark-2.2.3-bin-hadoop2.7.tgz
  - cd spark-2.2.3-bin-hadoop2.7
  - ls
  - ./sbin/start-master.sh
  - ls logs/
  - cat logs/spark-travis-org.apache.spark.deploy.master.Master-1-travis-job-d8cce8a0-e570-4f8f-8c97-6f13add3cd1b.out
  - sbt run

